### PR TITLE
Next.js migration

### LINKED ISSUE #105: Update Frontend to React 17
We should check all our dependencies for support of React 17 and see if there are any breaking changes. 

For now we need to wait for `restful-react` add support for it. https://github.com/contiamo/restful-react/issues/333

### LINKED ISSUE #182: Investigate frontend test failing occasionally
Our React tests sometimes fail on `Streams Explorer › handles url parameters › should update and retry if pipeline is not found`

```
Error: Error: Nock: No match for request {
        "method": "GET",
        "url": "http://localhost/api/graph?pipeline_name=avail-after-scrape",
        "headers": {
          "referer": "http://localhost/#/",
          "user-agent": "Mozilla/5.0 (linux) AppleWebKit/537.36 (KHTML, like Gecko) jsdom/11.12.0",
          "accept-language": "en",
          "accept": "*/*",
          "host": "localhost",
          "accept-encoding": "gzip, deflate"
        }
      }
```

The test succeeds after re-triggering the CI job.

### PR DESCRIPTION
**Pull request by disrupted**
Closes #105
Closes #182 

### Frontend

- [x] Migration to Next.js
	- modern replacement for Create-React-App
	- better build infra (JS transpiler) based on swc
	- fast refresh
- [x] Update to React 17
- [x] Migrated React router to Next router
- [x] Refactored G6 Graph component
	- Remove deprecated `ReactDOM.findDOMNode`
	- register callbacks outside useEffect hook
	- optimise render updates
- [x] Use native middleware instead of external dependency
- [x] Simplified tests (take advantage of Next router and react-testing-lib improvements)
- [x] Fix url params containing `pipeline=all%20pipelines` when it should be empty
- [x] Update all dependencies
	- 81 vulnerabilities → 20 vulnerabilities (13 moderate, 3 high, 4 critical)   
most of these seem to be related to restful-react afaict

### Backend

- [x] frontend is no longer served under `/static`, moved to url root `/`

### CODE REVIEW

File: frontend/components/App.tsx [hunk 1]
```diff
@@ -1,38 +1,36 @@
...
+import DetailsCard from "./DetailsCard";
+import { graphConfig } from "./graphConfiguration";
+import GraphVisualization from "./GraphVisualization";
+import Node from "./Node";
+import Settings from "./Settings";
 
 const { Header, Content } = Layout;
 
 const NodeIcon = ({ nodeType }: { nodeType: string }) => (
+  // TODO: switch to Image component
```
Comment (VictorKuenstler) [inline frontend/components/App.tsx:33]: Do you want do resolve this TODO in this PR?

File: frontend/components/App.tsx [hunk 2]
```diff
@@ -122,13 +120,9 @@ const App: React.FC = () => {
     error: metricsError,
   } = useGetMetricsApiMetricsGet({ lazy: true });
 
-  const getParams = useCallback(() => {
-    return new URLSearchParams(location.search);
-  }, [location.search]);
-
   function pushHistoryFocusNode(nodeId: string) {
```
Comment (VictorKuenstler) [inline frontend/components/App.tsx:123]: Method could be renamed to pushRouteFocueNode

File: frontend/components/DetailsCard.tsx [hunk 3]
```diff
@@ -13,7 +13,7 @@ const DetailsCard = ({ node }: DetailsCardProps) => {
   const ref = useRef<HTMLDivElement>(null!);
   const { width } = useResizeDetector({ targetRef: ref, handleHeight: false });
   return (
-    <div ref={ref} className="details">
+    <div ref={ref} className={style.details}>
```
Comment (VictorKuenstler) [inline frontend/components/DetailsCard.tsx:16]: nice :)

File: frontend/package.json [hunk 4]
```diff
@@ -1,73 +1,50 @@
...
-    "generate-fetcher": "restful-react import --file ../backend/docs/openapi.json --output ./src/api/fetchers.tsx",
-    "postgenerate-fetcher": "prettier ./src/api/fetchers.tsx --write",
-    "lint": "eslint --fix src/**/*.{ts,tsx}"
-  },
-  "eslintConfig": {
-    "extends": "react-app"
+    "dev": "next dev",
+    "lint": "next lint",
+    "build": "next build && next export",
+    "start": "next start",
```
Comment (VictorKuenstler) [inline frontend/package.json:9]: `next start` starts the server in production mode, right? To make it easier to differentiate we could rename the script from `start` to `prod`

File: frontend/package.json [hunk 5]
```diff
@@ -1,73 +1,50 @@
...
-  "homepage": "http://localhost/static"
+    "eslint": "7.32.0",
+    "eslint-config-next": "12.0.2",
+    "identity-obj-proxy": "^3.0.0",
+    "jest": "^27.3.1",
+    "jest-fix-undefined": "^0.1.2",
+    "next-router-mock": "^0.6.1",
+    "nock": "^13.1.4",
+    "react-test-renderer": "^17.0.2",
+    "whatwg-fetch": "^3.6.2"
```
Comment (VictorKuenstler) [inline frontend/package.json:48]: Why do we need this?

File: frontend/styles/global.css [hunk 6]
```diff
@@ -1,3 +1,17 @@
+body {
+  margin: 0;
+  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen",
```
Comment (VictorKuenstler) [inline frontend/styles/global.css:3]: I think the first font should be a font that is not operating systems dependent. Just to stay as consistent as possible :)

**Review by VictorKuenstler — CHANGES_REQUESTED** [review]

File: frontend/components/App.tsx (hunk 1 above)
Comment (disrupted) [reply frontend/components/App.tsx:33]: I tried it already, but it messed up the layout (vertically center the image on line), so I would visit this at a later point. Also I believe the improvements of Next image are more significant for larger images

**Review by VictorKuenstler — CHANGES_REQUESTED** [review]
image
The space between the menu items is a little too large on my screen now.

File: frontend/styles/global.css (hunk 6 above)
Comment (disrupted) [reply frontend/styles/global.css:3]: I didn't want to change that part as it's been our previous default https://github.com/bakdata/streams-explorer/blob/main/frontend/src/index.css

Should we leave it as it is or do you have a suggestion?

File: frontend/package.json (hunk 5 above)
Comment (disrupted) [reply frontend/package.json:48]: this is used for polyfilling some browser APIs (fetch) that are otherwise not available to Jest.

File: frontend/package.json (hunk 4 above)
Comment (disrupted) [reply frontend/package.json:9]: makes sense, I changed it :)

**Comment by disrupted** [comment]
> image
> The space between the menu items is a little too large on my screen now.

Do you use an ultrawide monitor? I've pushed a fix, but could only repro/verify it when resizing the window to gigantic sizes

**Comment by VictorKuenstler** [comment]
> > image
> > The space between the menu items is a little too large on my screen now.
> 
> Do you use an ultrawide monitor? I've pushed a fix, but could only repro/verify it when resizing the window to gigantic sizes

Not ultrawide but QHD. It looks good now 👍

File: frontend/styles/global.css (hunk 6 above)
Comment (VictorKuenstler) [reply frontend/styles/global.css:3]: Ah ok, lets keep it then :)

**Review by VictorKuenstler — APPROVED** [review]
